; Euler #4: largest palindrome from product of two 3-digit numbers (906609)
(defun putc (ch)
  (out ch))

(defun print_uint (val)
  (if (= val 0)
      (putc 48)
      (progn
        (putc (+ (/ val 100000) 48))
        (setq pr_rem (mod val 100000))
        (putc (+ (/ pr_rem 10000) 48))
        (setq pr_rem (mod pr_rem 10000))
        (putc (+ (/ pr_rem 1000) 48))
        (setq pr_rem (mod pr_rem 1000))
        (putc (+ (/ pr_rem 100) 48))
        (setq pr_rem (mod pr_rem 100))
        (putc (+ (/ pr_rem 10) 48))
        (putc (+ (mod pr_rem 10) 48)))))

(defun reverse3 (x)
  (+ (* (mod x 10) 100)
     (+ (* (mod (/ x 10) 10) 10)
        (/ x 100))))

(defun make_palindrome (left)
  (+ (* left 1000) (reverse3 left)))

(progn
  (setq high 999)
  (setq found 0)
  (setq best 0)
  (setq pal 0)
  (setq factor 0)
  (setq q 0)
  (setq inner_done 0)
  (loop (eq found 0)
    (if (< high 100)
        (setq found 1)
        (progn
          (setq pal (make_palindrome high))
          (setq factor 990)
          (setq inner_done 0)
          (loop (eq inner_done 0)
            (if (< factor 100)
                (setq inner_done 1)
                (progn
                  (if (eq (mod pal factor) 0)
                      (progn
                        (setq q (/ pal factor))
                        (if (< q 100)
                            0
                            (if (< q 1000)
                                (progn
                                  (setq best pal)
                                  (setq found 1)
                                  (setq inner_done 1))
                                0)))
                      0)
                  (setq factor (- factor 11)))))
          (if (eq found 0)
              (setq high (- high 1))
              0))))
  (print_uint best)
  (putc 10))
